WordPress-Theme/ruleset.xml
WordPress/Sniffs/Theme/NoAddAdminPagesSniff.php
WordPress/Tests/Theme/NoAddAdminPagesUnitTest.inc
WordPress/Tests/Theme/NoAddAdminPagesUnitTest.php

Closes #11.
[Edit] Changed over to use WordPress_Sniffs_Functions_FunctionRestrictionsSniff as the base class rather than Generic_Sniffs_PHP_ForbiddenFunctionsSniff.
This allows for better error messages, keeping it more in line with what people have come to expect from Theme Check.

Add sniff to check for `add_..._page()` functions + unit tests.

---

WordPress/Sniffs/Theme/DeprecatedWPConstantsSniff.php
WordPress/Tests/Theme/DeprecatedWPConstantsUnitTest.inc
WordPress/Tests/Theme/DeprecatedWPConstantsUnitTest.php

Covers the sniff + unit test for issue #23.
This PR covers the currently known list as can be found in: https://github.com/Otto42/theme-check/pull/162/files

Add sniff for deprecated Theme related WP Constants.

---

WordPress-Theme/ruleset.xml

This addresses the action item from #15 if the decision requested would follow the advice given.

Add rule to disallow alternative PHP open tags.

---

WordPress/Sniffs/Theme/FileIncludeSniff.php
WordPress/Tests/Theme/FileIncludeUnitTest.inc
WordPress/Tests/Theme/FileIncludeUnitTest.php

Issue #66
Check if include(_once) or require(_once) is used, and issue a warning to see if get_template_part() or locate_template() is more appropriate.

Warning for using include or require

---

WordPress/Sniffs/Theme/NoTitleTagSniff.php
WordPress/Tests/Theme/NoTitleTagUnitTest.inc
WordPress/Tests/Theme/NoTitleTagUnitTest.php

This addresses https://github.com/WPTRT/WordPress-Coding-Standards/issues/25

Add sniff to check that <title> tags are not used. 

---

WordPress-Theme/ruleset.xml

Execution of shell commands should be discouraged. A number of the other commands along the same lines are discouraged via function sniffs, however, the backtick operator was so far ignored.
As the TR branch has now merged the current WPCS version including the updated PHPCS 2.7 requirement, I can finally send this one in :sunglasses: 
See: https://github.com/squizlabs/PHP_CodeSniffer/pull/1073

Add rule to prohibit the use of the backtick shell execution operator.

---

WordPress-Theme/ruleset.xml

The check should prevent mixed line endings.
fixes #3 & #4
These are the test files that I created and used.
[mixed-line-endings.zip](https://github.com/WPTRT/WordPress-Coding-Standards/files/658861/mixed-line-endings.zip)

Mark mixed line endings as error

---

WordPress-Theme/ruleset.xml

See https://github.com/WPTRT/WordPress-Coding-Standards/issues/83#issuecomment-268009879
@emiluzelac Care to test with this branch ?
FYI: in this case the specific sniff referenced has a public property which determines whether the sniff should throw a warning or an error. The property defaults to `false` (=warning), so changing the property to `true` fixes this. This also changes the error code the sniff uses which is why - in this case - this is the more appropriate way to change the error type.

Change error silencing rule from warning to error.

---

WordPress-Theme/ruleset.xml

I missed one error notice in https://github.com/WPTRT/WordPress-Coding-Standards/pull/89

Mark MissingUnslash as Warning

---

WordPress-Theme/ruleset.xml

To be merged once upstream has been merged back. Upstream PR https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/736 (already merged) contains a number of bug fixes which make this acceptable for use. Before that it was throwing too many false positives. See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/300
Oh and before anyone asks: the `$content_width` variable is already excepted from the upstream sniff.

Prohibit overwriting of WP global variables

---

WordPress-Theme/ruleset.xml

The `eval()` check used to be done through a function restriction sniff, but eval is a language construct, not a function.
Upstream this has now been changed, so it makes sense to apply the same change here.
See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/812

Prohibit the use of the eval() language construct in themes.

---

WordPress/Sniffs/Theme/NoTitleTagSniff.php

Extend the `WordPress_Sniff` and use the now merged upstream `has_html_open_tag()` method.
Can be merged once the upstream changes have been merged into this repo.

NoTitleTag: Defer to upstream `has_html_open_tag()` method.

---

WordPress-Theme/ruleset.xml

Actual validation of this won't happen until the next back-merge from upstream, but this should allow the build for the back-merge to pass ;-)
----
N.B.: the build failure is unrelated to this PR and has already been solved upstream via https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/912. A backmerge would solve it for this fork too.

CS: Fix code style of the ruleset as per the new upstream guidelines.

---

WordPress/Tests/Theme/NoAutoGenerateUnitTest.php

`break` is superfluous if the code above it already returns out of the function call.
----
N.B.: the build failure is unrelated to this PR and has already been solved upstream via https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/912. A backmerge would solve it for this fork too.

Minor code clean-up.

---

WordPress-Theme/ruleset.xml

~~:warning: This PR should not be merged until WPCS has been merged back into the TRTCS as the sniff has only recently been added to WPCS.~~
Rebased after the merge of #145. Merging should now be fine.
Fixes #129

Add `PrefixAllGlobals` sniff to the ruleset.

---

WordPress/Sniffs/Theme/NoAutoGenerateSniff.php
WordPress/Sniffs/Theme/NoFaviconSniff.php
WordPress/Sniffs/Theme/NoTitleTagSniff.php

~~:warning: This PR should not be merged until WPCS has been merged back into the TRTCS as the WPCS minimum requirement of PHPCS 2.9.0 has only recently been changed in WPCS (as PHPCS 2.9.0 has only just been released).~~
Rebased after the merge of #145. Amended the original commit with a minor change for PHPCS 3.x compatibility. Merging should now be fine.
Fixes #128

PHPCS 2.9.0: Update sniffs to use the new `PHP_CodeSniffer_Tokens::$textStringTokens` token array.

---

WordPress-Theme/ruleset.xml

~~:warning: This PR should not be merged until WPCS has been merged back into the TRTCS as the sniff has only recently been added to WPCS.~~
Rebased after the merge of #145. Merging should now be fine.
Fixes #88

Add `CapitalPDangit` sniff to the ruleset and turn it into an error.

---

WordPress-Theme/ruleset.xml

This is the default in PHPCS 3.x, but should be set for maximum portability and documentation of how files will be treated.

Ruleset: treat all files as UTF-8

---

WordPress-Theme/ruleset.xml

Not having a PHP closing tag if it would be the last thing in a file is best practice which should be adhered to as this can prevent PHP "headers already send" errors.
While this is not explicitly mentioned in the handbook, this can be considered to fall under the "Required: No PHP notices" rule.
Ref: https://make.wordpress.org/themes/handbook/review/required/explanations-and-examples/#code

Prohibit PHP closing tag at end of PHP-only file

---

WordPress-Theme/ruleset.xml

Add a sniff to the ruleset which will warn on completely empty statements `<?php     ?>`. The sniff includes a fixer to remove these superfluous tags.

Warn on empty statements

---

WordPress-Theme/ruleset.xml

Adds two new upstream WPCS sniffs to the ruleset.
These sniffs will throw a `warning` if the class/function parameter was deprecated in any of the last three minors and an `error` if the class/parameter was deprecated before that.
(Partially) Fixes #72

Detect usage of deprecated WP classes and function call parameters

---

WordPress-Theme/ruleset.xml

Adds four new sniffs from WPCS to the ruleset:
* `DB.RestrictedClasses` and `DB.RestrictedFunctions` will throw `error`s when usage of the PHP native DB functions and classes is detected.
* `WP.PreparedSQL` tries to find SQL queries with placeholders and will throw an `error` when the query is not (late) prepared.
* `DB.PreparedSQLPlaceholders` verifies that placeholders are used correctly in prepared queries to prevent issues related to the security holes patched in WP 4.8.x.

Add upstream DB related sniffs

---

WordPress/Sniffs/Theme/NoAddAdminPagesSniff.php
WordPress/Tests/Theme/NoAddAdminPagesUnitTest.inc
WordPress/Tests/Theme/NoAddAdminPagesUnitTest.php

Even though the _Links_ menu is now disabled for new installs, the functionality does still exist and the function to add submenus to it has not been deprecated, so should be included in this sniff.

NoAddAdminPages: add `add_links_page()` to the functions list

---

WordPress-Theme/ruleset.xml

Themes should never need to access session data. These two sniffs make sure that errors are thrown when the PHP session functions are used, as well as when the `$_SESSION` global is accessed.

Add sniffs to detect accessing session data

---

WordPress-Theme/ruleset.xml

This adds an upstream sniff which can check for whitespace before a PHP open tag.
As the sniff does more than just that, all other error codes from the sniff are excluded.
The check takes inline HTML into account and will not throw an error if the PHP open tag is not the first non-whitespace token in the file.
Notes:
* Changed the error message to make it very clear why this check is here.
* The upstream sniff does not handle unicode whitespace well. This is being discussed in an issue I opened upstream and will probably/hopefully be fixed soon.
Fixes #148

Add check for whitespace before PHP open tag

---

README.md
WPThemeReview/ruleset.xml
composer.json

This currently presumes that all themes should be compatible with PHP 5.2-nightly.
At a later point in time, we may be able to make this more configurable by reading out the `Requires PHP:` header in the `style.css` file and, if found, using the minimum PHP version set there for the bottom limit in `testVersion`.
For now, the `testVersion` as set in the ruleset can be overruled from the command-line by passing a `testVersion` as a command-line parameter, like so: `phpcs ... --runtime-set testVersion 5.4-`.
Fixes #173

Ruleset: add the PHPCompatibilityWP standard

---

README.md
composer.json

[PHPCompatibility 9.0.0](https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/9.0.0) has just been released and renames all sniffs.
[PHPCompatibilityWP 2.0.0](https://github.com/PHPCompatibility/PHPCompatibilityWP/releases/tag/2.0.0) has been released alongside it.
The upgrade for this repo is simple as TRTCS currently doesn't use PHPCS inline annotations which reference PHPCompatibility sniffs, nor uses custom excludes.
As the PHPCompatibilityWP ruleset as of version 2.0 has an additional dependency, it is however opportune to let the DealerDirect plugin sort out the installed paths, at least for devs.
For end-users, the DealerDirect plugin is advised anyway, so hopefully people will listen to that advice ;-)
* Updated the version restrictions in `composer.json`.
* Removed …

Update for PHPCompatibility 9.0.0

---

WPThemeReview/ruleset.xml

Introduced by #182.
Sometimes things get confusing. This sniff is currently already part of WPCS, but is called `WordPress.CodeAnalysis.EmptyStatement`.
The upstream PHPCS version for which the PR has been open for nine months so far, is called `Generic.CodeAnalysis.EmptyPHPStatement`.
My bad for getting the names mixed up ;-)
Fixes #185

Ruleset: bug fix

---

composer.json

WPCS 1.2.0 has just been released: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.2.0
As it is important that themes which use namespaces prefix those namespaces with a theme specific prefix, I suggest upping the minium WPCS version to 1.2.0, which includes a check for that.

Update to use WPCS 1.2.0

---

README.md
composer.json

> Below 1.0 minor releases are treated as major releases so `^` locks to current minor release.
Ref: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1628
Props @Rarst
Version 0.5.0 was released in October 2018, so should be used by now.
Ref: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases

Bump suggested installer version

---

.travis.yml

Nightly has become PHP 8.0 since PHP 7.4 has been branched, so to continue to also test against PHP 7.4, it needs to be added separately.
Refs:
* https://twitter.com/nikita_ppv/status/1089839541828112384
* https://twitter.com/nikita_ppv/status/1094897743594770433
As of recently, the Travis images for PHP 7.2+ ship with PHPUnit 8.x.
The PHPCS native test framework is not compatible with PHPUnit 8.x and won't be able to be made compatible with it until the minimum PHP version would be raised to PHP 7.1.
So for the unit tests to be able to run on PHP 7.2+, we need to explicitly require PHPUnit 7.x for those builds.
As for nightly: there is no PHPUnit version which is currently compatible with PHP 8.
As that either means that the builds for `nightly` would always fail or - if the unit tests …

Travis: test builds against PHP 7.4 & work around for PHPUnit 8

---

WPThemeReview/ruleset.xml

Messages in `Squiz.WhiteSpace.SuperfluousWhitespace.StartFile`, and `PSR2.Files.ClosingTag.NotAllowed` reference "headers already send", but should be "headers already sent".  Added a missing comma for `PSR2.Files.ClosingTag.NotAllowed` message as well.

fixing headers already sent message

---

.travis.yml

As there are quite some sniffs which now extend WPCS sniffs, it would be prudent to test builds against a mix of PHPCS and WPCS versions.
With the changes made in this PR, all sniffs will be tested against a combination of the highest PHPCS+WPCS versions as well as the lowest PHPCS+WPCS versions on most PHP versions.
To also make sure that the sniffs work correctly with a different combi, the PHP 7.2 build will test with high PHPCS vs low WPCS and with low PHPCS vs high WPCS.

Travis: test against high/low WPCS

---

.travis.yml
README.md
composer.json

WPCS 2.1.0 has been released and contains quite some bug fixes, most notably in the security related sniffs.
Ref: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/2.1.0
Includes removing a reference to `WordPress-VIP` from the readme. `WordPress-VIP` was removed in WPCS 2.0.0.

Composer: use WPCS ^2.1.0

---

WPThemeReview/ruleset.xml

Add rule that forbids the setting of INI configuration in themes.
Related issue #209

Add rule about setting INI during runtime in themes

---

.travis.yml

Travis will (soon, if not already) no longer support this directive: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Travis: remove `sudo: false`

---

.phpcs.xml.dist
.travis.yml
WPThemeReview/ruleset.xml

As of PHPCS 3.2.0, PHPCS includes an XSD schema for rulesets which defines what can be used in the XML ruleset file.
In PHPCS 3.3.0 a new array format for properties was introduced and as of PHPCS 3.3.2, the new array format is now also covered by this schema.
This commit:
* Adds the schema tags to the `ruleset.xml` files and the WPTRTCS native `.phpcs.xml.dist` file.
* Adds validation against the schema for the `ruleset.xml` file to the Travis build.
Fixes #175

Rulesets: Add XSD schema tags and validate rulesets against schema (PHPCS 3.2+/3.3.2+)

---

.travis.yml

Travis now offers stages. Using stages we can:
- Run the code style related checks before running any unit tests and stop the build early if any are detected.
While this does mean that the unit tests will run with a slight delay (the `Sniff` stage has to finish before they start), it also means that we:
* Get code style errors reported earlier as it's been moved to be the first stage and the build will just stop if any are found.
* We won't be wasting Travis's resources on builds which will have to be re-run anyway.
* The output of the Travis jobs will be a lot easier to decipher as it only shows the output related to that particular stage.
Ref: https://docs.travis-ci.com/user/build-stages/
Note that `Allowed failures` is no longer listed as a separate block in the Travis result overview, …

Travis: run the code style related and ruleset checks in separate stages

---

WPThemeReview/Sniffs/CoreFunctionality/PostsPerPageSniff.php
WPThemeReview/Tests/CoreFunctionality/PostsPerPageUnitTest.inc
WPThemeReview/Tests/CoreFunctionality/PostsPerPageUnitTest.php
WPThemeReview/ruleset.xml

As noted in the issue #147 there was an agreement in the meeting to use the posts per page sniff, but that the ruleset should throw a warning instead of an error.

Include post per page rule and make it into a warning

---

WPThemeReview/Sniffs/Templates/ReservedFileNamePrefixSniff.php
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/-tag.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/Page-info.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/category-.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/category-books.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/front-contact.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/index-secondary.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/page-contact-form.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/page.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixTests/tmplt-contact.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixUnitTest.inc
WPThemeReview/Tests/Templates/ReservedFileNamePrefixUnitTest.php

This is a PR for #212 issue.
I'm sure more test cases would be a good idea, and I'm not 100% sure if I should check for the comment at all, or just check for prefixed file names.
One thing that I had to add was `strip_quotes` method from the WPCS `Sniff` abstract class.
Should I have just extended that sniff instead of implementing the `Sniff` interface from PHPCS (seeing how WPCS's abstract `Sniff` class already implements it).

Add Reserved Template Name Sniff

---

WPThemeReview/Sniffs/CoreFunctionality/PrefixAllGlobalsSniff.php

WPCS 2.2.0 changes the method signature of the `PrefixAllGlobalsSniff::process_variable_assignment()` method, adding a new `$in_list` parameter.
This means that the method signature for the method as overloaded in WPTRTCS needs to be updated to prevent the following PHP warning `Declaration of WPThemeReview\Sniffs\CoreFunctionality\PrefixAllGlobalsSniff::process_variable_assignment($stackPtr) should be compatible with WordPressCS\WordPress\Sniffs\NamingConventions\PrefixAllGlobalsSniff::process_variable_assignment($stackPtr, $in_list = false)`.
It it safe to add this new parameter to WPThemeReview already, even though WPCS 2.2.0 hasn't been released yet, as passing _too many_ parameters to a function and/or adding an additional parameter to an overloaded method in a child class does not …

PrefixAllGlobals: update method signature for compatibility with WPCS 2.2.0

---

WPThemeReview/Sniffs/CoreFunctionality/PrefixAllGlobalsSniff.php

Since WPCS 2.2.0 was released, I'm getting errors when working with theme sniffer (I updated the packages), so I thought we'd release this as a part of the 0.2.1. hotfix release (I'll try to sort the rest of the issues in some reasonable milestones so that we get this thing going).

PrefixAllGlobals sniff - add the version number in the docblock
