WPTRT/WPThemeReview

- WordPress-Theme/ruleset.xml
This addresses the action item from #2 if the decision requested would follow the advice given.
> Add rule to disallow PHP short open tags.

- WordPress-Theme/ruleset.xml
This addresses the action item from #3 if the decision requested would follow the advice given.
> Add rule to only allow UNIX style line endings.

- WordPress-Theme/ruleset.xml
This addresses the action item from #5 if the decision requested would follow the advice given.
> Add rule to disallow Unicode ByteOrderMarks in files.

- WordPress-Theme/ruleset.xml
> Check that the I18N functions are used correctly.

- WordPress-Theme/ruleset.xml
This addresses the action item from #39 if the decision requested would follow the suggestion made.
> Add sniff to verify that scripts and styles are enqueued.

- WordPress-Theme/ruleset.xml
This addresses the action item from #18 if the decision requested would follow the advice given.
> Add rule to prevent path disclosure when using add_theme_page().

- WordPress-Theme/ruleset.xml
> Add Generic.PHP.NoSilencedErrors

- WordPress/Sniffs/Theme/PluginTerritoryFunctionsSniff.php
- WordPress/Tests/Theme/PluginTerritoryFunctionsUnitTest.inc
- WordPress/Tests/Theme/PluginTerritoryFunctionsUnitTest.php
> Plugin Territory Functions

- WordPress-Theme/ruleset.xml
Check for validation/sanitization of all input, escaping of all output.
Fixes #37
> Add existing sniffs to validate all input, escape all output.

- WordPress/Sniffs/Theme/NoFaviconSniff.php
- WordPress/Tests/Theme/NoFaviconUnitTest.inc
- WordPress/Tests/Theme/NoFaviconUnitTest.php
> No Favicon

- WordPress-Theme/ruleset.xml
Somehow the previous fix did not work for me but this way works.
fixes #37
> Lowered the error level to warning

- WordPress/Sniffs/Theme/NoFaviconSniff.php
- WordPress/Tests/Theme/NoFaviconUnitTest.inc
- WordPress/Tests/Theme/NoFaviconUnitTest.php
> NoFaviconSniff: Add Heredoc and Nowdoc support.

- WordPress/Sniffs/Theme/NoTitleTagSniff.php
- WordPress/Tests/Theme/NoTitleTagUnitTest.inc
- WordPress/Tests/Theme/NoTitleTagUnitTest.php
> NoTitleTag: Add Heredoc and Nowdoc support.

- WordPress/Sniffs/Theme/NoAutoGenerateSniff.php
- WordPress/Tests/Theme/NoAutoGenerateUnitTest.inc
- WordPress/Tests/Theme/NoAutoGenerateUnitTest.php
> NoAutoGenerate: Add Heredoc and Nowdoc support.

- WordPress-Theme/ruleset.xml
> Add rule to disallow removal of the admin bar.

- WordPress-Theme/ruleset.xml
> Deprecated WordPress Functions

- WordPress-Theme/ruleset.xml
> Ruleset: bug fix - use the correct sniffname

- WordPress-Theme/ruleset.xml
As discussed in the meeting last Thursday.
> Add sniff to detect timezone changing

- .github/ISSUE_TEMPLATE
* Add a small table at the top of the issue which contains the basic info.
This includes adding `Sniff Category` to the template.
* Move a lot of explanations of what info should be added to the issue into comment tags.
* Improve the section headers style.
* Add an explicit section asking for code samples.
> Issue template: textual update

- autoload.php
Composer project based install wasn't sufficiently supported. This small change fixes that.
Fixes #184
> Autoload: bug fix

- .github/CONTRIBUTING.md
Added the contributing template.
> Add contributing template

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE
- .travis.yml
- CHANGELOG.md
- README.md
- WPThemeReview/ruleset.xml
- autoload.php
- composer.json
Let's get this baby out of the door!
> Release version 0.1.0

- WPThemeReview/ruleset.xml
From issue #171 added deprecated parameter values rule in the ruleset.
> Add deprecated parameter values rule in the ruleset

- WPThemeReview/Sniffs/PluginTerritory/ForbiddenFunctionsSniff.php
- WPThemeReview/Tests/PluginTerritory/ForbiddenFunctionsUnitTest.inc
- WPThemeReview/Tests/PluginTerritory/ForbiddenFunctionsUnitTest.php
> Update forbidden functionality with cron functions

- .github/CONTRIBUTING.md
- CHANGELOG.md
- README.md
- WPThemeReview/Sniffs/Plugins/CorrectTGMPAVersionSniff.php
- WPThemeReview/ruleset.xml
I've updated the changelog and replaced old links of WPCS github repository with the new one.
Once this is merged I can tag and release 0.2.0 version 🎉
> Minor prerelease updates

- CHANGELOG.md
I have targeted the release for November 17th, if that's not a problem.
Let me know if this looks ok.
> Update changelog for 0.2.1 hotfix release
